[package]
name = "introduction-pods"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
itertools = "0.14.0"
strum = "0.26"
strum_macros = "0.26"
anyhow = "1.0.56"
dyn-clone = "1.0.18"
log = "0.4"
env_logger = "0.11"
lazy_static = "1.5.0"
thiserror = { version = "2.0.12" }
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2" }
serde = "1.0.219"
serde_json = "1.0.140"
base64 = "0.22.1"
schemars = "0.8.22"
hashbrown = { version = "0.14.3", default-features = false, features = ["serde"] }
num = { version = "0.4.0", default-features = false }

pod2 = { git="https://github.com/0xPARC/pod2" }

[features]
default = []
metrics = ["pod2/metrics"]
time = ["pod2/time"]
